// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssijHkDnncEdpsMXaFkiNf5ClSO0dkU8',
    appId: '1:878795926479:web:56a6b3d89d2a62fcb880ba',
    messagingSenderId: '878795926479',
    projectId: 'trafix-3d86b',
    authDomain: 'trafix-3d86b.firebaseapp.com',
    storageBucket: 'trafix-3d86b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ep4JLTIHevbpmNh1k4BHkvoxQrWFxg4',
    appId: '1:878795926479:android:261cbafb56176526b880ba',
    messagingSenderId: '878795926479',
    projectId: 'trafix-3d86b',
    storageBucket: 'trafix-3d86b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-esiDhwWeSPErAX3E_ffceP8j_xZ_M-U',
    appId: '1:878795926479:ios:c9b5d0bd9a8e064ab880ba',
    messagingSenderId: '878795926479',
    projectId: 'trafix-3d86b',
    storageBucket: 'trafix-3d86b.firebasestorage.app',
    iosBundleId: 'com.example.trafix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-esiDhwWeSPErAX3E_ffceP8j_xZ_M-U',
    appId: '1:878795926479:ios:c9b5d0bd9a8e064ab880ba',
    messagingSenderId: '878795926479',
    projectId: 'trafix-3d86b',
    storageBucket: 'trafix-3d86b.firebasestorage.app',
    iosBundleId: 'com.example.trafix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssijHkDnncEdpsMXaFkiNf5ClSO0dkU8',
    appId: '1:878795926479:web:3fc5cdfc0271c2a7b880ba',
    messagingSenderId: '878795926479',
    projectId: 'trafix-3d86b',
    authDomain: 'trafix-3d86b.firebaseapp.com',
    storageBucket: 'trafix-3d86b.firebasestorage.app',
  );
}
